version: '3'
services:
  gmo-api:
    restart: always
    build: .
    ports:
     - "8080:8080"
    image: catm0308/gmoapi
    container_name: 'gmoapi'
    tty: true
    volumes:
      - ./opt:/project/opt
    command: flask run --host 0.0.0.0 --port 8080
